# Generated by Django 4.2.7 on 2025-03-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_question_code_language_question_is_code_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='code_language',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_code_question',
        ),
        migrations.AddField(
            model_name='question',
            name='code_snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
