# Generated by Django 5.2.12 on 2026-03-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0006_question_constraints_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='submitted_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='chosen_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
