# Generated by Django 5.2.12 on 2026-03-22 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0009_student_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='code_snippet',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'question')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['round_number'], name='quiz_api_qu_round_n_279761_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['round_number', 'difficulty'], name='quiz_api_qu_round_n_b08f88_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-total_score'], name='quiz_api_st_total_s_8d54e6_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='quiz_api_st_email_c300a3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['round2_qualified'], name='quiz_api_st_round2__3feed3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['student', 'round_number'], name='quiz_api_st_student_1ffaa3_idx'),
        ),
    ]
