# Generated by Django 5.2.12 on 2026-03-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0011_question_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='code_snippet',
            new_name='code_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
        migrations.AddField(
            model_name='question',
            name='code_java',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='code_python',
            field=models.TextField(blank=True, default=''),
        ),
    ]
