# Generated by Django 5.2.12 on 2026-03-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0012_rename_code_snippet_question_code_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_cases_c',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='test_cases_java',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='test_cases_python',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
